#!/bin/bash

ls -tu --ignore='.*' --ignore='.' --ignore='..' --group-directories-first | \
while read entry; do
    if [ -d "$entry" ]; then
        echo "$entry/"
    else
        echo "$entry"
    fi
done | paste -sd, -